from rest_framework import serializers
from apibackendapp.models import (
    LabTest,
    LabTestPrescription,
    Appointment,
    Patient,
    LabTestReport,
    Billing,
    Doctor,
    Consultation
)

# -------------------------
# PATIENT SERIALIZER
# -------------------------

class PatientSerializer(serializers.ModelSerializer):
    age = serializers.SerializerMethodField()

    class Meta:
        model = Patient
        fields = [
            "patient_id",
            "patient_name",
            "date_of_birth",
            "gender",
            "contact_info",
            "address",
            "blood_group",
            "age",
        ]

    def get_age(self, obj):
        if not obj.date_of_birth:
            return None
        from datetime import date
        return date.today().year - obj.date_of_birth.year


# -------------------------
# LAB TEST SERIALIZER
# -------------------------

class LabTestSerializer(serializers.ModelSerializer):
    lab_test_id = serializers.CharField(read_only=True)  # Auto-generated by signal

    class Meta:
        model = LabTest
        fields = [
            "lab_test_id",
            "lab_test_name",
            "amount",
            "min_range",
            "max_range",
            "sample_collected",
        ]


# -------------------------
# LAB TEST PRESCRIPTION SERIALIZER
# -------------------------

class LabTestPrescriptionSerializer(serializers.ModelSerializer):
    lab_test_details = LabTestSerializer(source="lab_test", read_only=True)

    class Meta:
        model = LabTestPrescription
        fields = [
            "lab_test_prescription_id",
            "lab_test",
            "lab_test_details",
            "lab_test_value",
            "created_date",
            "remarks",
            "appointment",
        ]

    def validate(self, data):
        """Ensure both appointment & lab test exist"""
        if not data.get("appointment"):
            raise serializers.ValidationError("Appointment is required.")
        
        if not data.get("lab_test"):
            raise serializers.ValidationError("Lab Test is required.")

        return data


# -------------------------
# LAB TEST REPORT SERIALIZER
# -------------------------

class LabTestReportSerializer(serializers.ModelSerializer):
    patient = PatientSerializer(read_only=True)
    doctor_name = serializers.CharField(source="doctor.name", read_only=True)
    staff_name = serializers.CharField(source="staff.fullname", read_only=True)

    class Meta:
        model = LabTestReport
        fields = [
            "report_id",
            "appointment",
            "patient",
            "doctor",
            "doctor_name",
            "staff",
            "staff_name",
            "report_date",
            "overall_remarks",
            "report_status",
        ]

    def validate(self, data):
        """Ensure report can only be generated if tests are prescribed."""
        appointment = data.get("appointment")

        # Check if prescription exists for this appointment
        if not LabTestPrescription.objects.filter(appointment=appointment).exists():
            raise serializers.ValidationError(
                "No lab test prescriptions found for this appointment."
            )

        return data


# -------------------------
# BILLING SERIALIZER
# -------------------------

class BillingSerializer(serializers.ModelSerializer):
    patient_name = serializers.CharField(source="patient.patient_name", read_only=True)

    class Meta:
        model = Billing
        fields = [
            "bill_id",
            "patient",
            "patient_name",
            "bill_date",
            "amount_due",
            "due_date",
            "payment_status",
        ]

    def validate(self, data):
        if not data.get("patient"):
            raise serializers.ValidationError("Patient is required to generate billing.")
        return data

    def create(self, validated_data):
        """Auto calculate total amount due based on patient’s lab tests."""
        billing = super().create(validated_data)

        total = 0
        appointments = Appointment.objects.filter(patient=billing.patient)

        for app in appointments:
            prescriptions = LabTestPrescription.objects.filter(appointment=app)
            for pres in prescriptions:
                total += pres.lab_test.amount or 0
        
        billing.amount_due = total
        billing.save()
        return billing
