# Generated by Django 5.2.8 on 2025-11-19 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labtec', '__first__'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reception.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fulfill_pharmacist_internally', models.BooleanField(default=True)),
                ('fulfill_lab_internally', models.BooleanField(default=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reception.appointment')),
                ('vitals', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.basicvitals')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_orders', to='doctor.consultation')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labtec.labtestcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=10)),
                ('frequency', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=10)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='doctor.consultation')),
            ],
        ),
    ]
