# Generated by Django 5.2.7 on 2025-11-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('token_number', models.IntegerField(blank=True, null=True)),
                ('consultation_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tblappointment',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('contact_info', models.IntegerField(blank=True, null=True)),
                ('consultation_fee', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbldoctor',
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('lab_test_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lab_test_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('min_range', models.IntegerField(blank=True, null=True)),
                ('max_range', models.IntegerField(blank=True, null=True)),
                ('sample_collected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tblLabtest',
            },
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('medicine_category_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('medicine_category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblmedicinecategory',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tblpatient',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblrole',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblspecialization',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('mail_id', models.CharField(blank=True, max_length=30, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tblstaff',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.appointment')),
            ],
            options={
                'db_table': 'tblconsultation',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor'),
        ),
        migrations.CreateModel(
            name='LabTestPrescription',
            fields=[
                ('lab_test_prescription_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lab_test_value', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.appointment')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.labtest')),
            ],
            options={
                'db_table': 'tblLabtestprescription',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('medicine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.medicinecategory')),
            ],
            options={
                'db_table': 'tblmedicine',
            },
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('medicine_prescription_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dosage', models.IntegerField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.appointment')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.medicine')),
            ],
            options={
                'db_table': 'tblmedicineprescription',
            },
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('medicine_stock_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stock_in_hand', models.IntegerField(default=0)),
                ('re_order_level', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.medicine')),
            ],
            options={
                'db_table': 'tblmedicinestock',
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bill_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient')),
            ],
            options={
                'db_table': 'tblbilling',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.specialization'),
        ),
        migrations.CreateModel(
            name='LabTestReport',
            fields=[
                ('report_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('overall_remarks', models.TextField(blank=True, null=True)),
                ('report_status', models.CharField(default='Pending', max_length=20)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.staff')),
            ],
            options={
                'db_table': 'tblLabtestreport',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.role')),
            ],
            options={
                'db_table': 'tblUser',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.systemuser'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.systemuser'),
        ),
    ]
