# Generated by Django 5.2.8 on 2025-11-19 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0002_remove_systemuser_role_alter_staff_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblrole',
            },
        ),
        migrations.AlterField(
            model_name='labtest',
            name='lab_test_id',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.role')),
            ],
            options={
                'db_table': 'tblUser',
            },
        ),
    ]
